version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    depends_on:
      - mysql
    volumes:
      - ./:/app:delegated
    ports:
      - $DOCKER_WEB_PORT:80

  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - $DOCKER_MYSQL_PORT:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - $DOCKER_ADMINER_PORT:8080
